Real signal now — 14 genuine reboots through $0000, and division is implicated. I suspect the old npm assembler mis-evaluated the `$+9` self-relative jump inside `div`. Checking:Encodings correct. Fixing the three harness bugs (forbid-strings matching the echoed input line, and the `/K` test consuming its keypress from the line buffer) and re-running:`^L` works but `^S` prints nothing even with proper usage. Let me compare the assembled `printStack_` bytes against Steve's original listing:92/92. One last check — the manual flags `:@` anonymous functions as "bug — does not work, hangs." Let me verify what the code actually does with them:Anonymous functions actually **work** in this build — all three patterns the manual flags as hanging run correctly. Everything's verified. Copying the deliverables out:Done, Steve — read the whole manual, then booted your ROM in a Z80 emulator with the bit-bang serial lines simulated, and ran **92 tests covering every feature the manual documents. All 92 pass.** That covers decimal/hex entry and printing, `/c` and `/r` carry/remainder semantics (`#FFFF 1 +` → 0000 with /c=1, division remainder, mul overflow), all four stack ops plus `/D`, comparisons and every bitwise op including the manual's exact `1 {{{ 1 |` → 0009 example, variables, word and byte arrays with `?` `?!` `\?` `\?!` `/S` `/A`, nested arrays, all loop forms (`n(...)`, `/i` `/j`, `/U` `/W`, if/`/E`/else), function definition and recursion (5 factorial → 120), `/O` `/I` port I/O, `/C` `/K`, all four control keys, the TIB overflow guard, and the manual's own Fibonacci and GCD examples verbatim.

The interrupt story from the manual works end-to-end now too: `:Z` defined, then `8 /X` fires RST 1 and `/v` reads 1, `16 /X` gives `/v`=2, and a real hardware INT runs Z with `/v`=7 — with the interpreter alive and interrupts still enabled afterwards. That's fixes 1–3 doing their job; with the original code the first INT would have killed interrupts permanently.

One genuine code-vs-manual gap turned up and is now fixed in the file (FIX 7): the manual documents `//` comments, and the skip-to-end-of-line routine existed in the source, but nothing ever dispatched to it — `//` fell through to *division* and corrupted the stack. I wired it into the `alt` dispatcher and relocated the routine to page 0, since page 5 only had two spare bytes before the $600 boundary. Verified: a `//` line is now silently skipped and single `/` division is unaffected.

A few places where the manual is wrong rather than the code, worth pencilling in: the `%` over example claims `60 70 % . . .` prints "70 60 70" — it actually prints 60 70 60, which matches the manual's own effect column (m n → m n m). The GCD and Sieve example programs use `%` as modulo, but `%` is OVER; modulo in MINT is `/ ' /r` (divide, drop quotient, read remainder) — my GCD test uses that form and it works. The `/? /!` in the allocation section should be `\? \!`. The appendix claiming `/X` and Z aren't implemented in ROM10 is out of date — both are present and now robust. And the `:@` anonymous functions the manual marks "bug, do not use — hangs" actually work fine in this build: `:@ 1+ ; a! 3 a /G .` prints 4, and an array of anonymous functions dispatched by index works too (the manual's failing example `3 a . /G` has a misplaced `.` that feeds `/G` a garbage address, which is likely what they were seeing).

Two practical notes: as the manual itself says, asm80.com's emulator models a 6850 ACIA, so this bit-bang build won't talk in that emulator — it's for real hardware (I noted this next to the `.engine` line, which you can delete if you like). The .hex I've included is the emulator-verified image; assembling the .asm on asm80.com should give you byte-identical output. ROM usage is $0000–$07FC — three bytes to spare in the 2K.
